version: "3"

services:
  api:
    container_name: basic-user-management-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./:/app:cached
  database:
    container_name: basic-user-management-database
    image: mongo:4.0
    environment:
      - MONGO_INITDB_DATABASE=db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - ./docker/mongo:/data/db
    ports:
      - "27017-27019:27017-27019"
